before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: mvtHUqvn8CXAJCYHwGGkAKUcoSAMkMQpvyU21t7MI+C1jY7otU2O9aV+c2DagX83LLIvy7BfO9fOuHBtGqjY1UoeUvMeAftV3IZKcSsiCRlET+amZaHER8VOtcp9nMsWP8FThjomQB4xQ/Z/RnqsXcXXoQTKO3VpEsmsTEMcfUA4xes/C37BTzmEm/m0wlWBxEg0D31y16j8ziJvcKpI8asDb8mwnemKsOA+OznIM5C3UsSgk4x8gonAjG9SmEpp/ZC/AGRaynIfFgwcto0QVBLU3hCVArdE7LUh11s3MRS9zzvwSuWPi+GRdLrA++i34eK7uPEU3guz3emMomcmt+dAlHAQQCq7Ft1EM5QUNAD4ETYDBGZGlNEOjYAaZj4sulaJVO56Sll1vbHivWwghgR3whReLrfl8sbZk6ZTJakZIRh0XPU/ZhbzS1PeyYfcubj2z/U8wP9bKwLHvv/DzfFgX7ywuwtZIETNNBuLmBteO/S6M7chOUhFUTOG9eqKnA+fdUYrAUEpo6PMl2s8kIa5s0cEL0aAmA3V927X4l7sZ3x4RFBJ2+TmUWu9wyHcy5+ADbhzs9fxQY8GqOH6GWHJ78I3b3VQRCoebGDeWXtaFxs0h0rWCZ+Bskr3kz6iyeBUkO+3fx/Y/Qor5dbUIx0GbXjb/kPMM2VpR/+N3Pc= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
